title: Distrust
email: info@distrust.co
description: Security without blind trust.
baseurl: ""
url: "https://distrust.co"
banner: "https://distrust.co/assets/base/distrust-thumbnail.png"

header_pages:
- index.md
- services.md
- software.md
- company.md
- blog.md
- contact.md

style: dark
listen_for_clients_preferred_style: false

footer: 'Â© 2025 Caution LLC'

theme: jekyll-theme-console

permalink: blog/:title.html

plugins:
- jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
